import type { AppLanguage } from './i18n'

export type DashboardSection =
  | 'overview'
  | 'memory'
  | 'tasks'
  | 'radio'
  | 'dispatch'
  | 'workflows'
  | 'analytics'
  | 'backups'
  | 'search'
  | 'tools'
  | 'projects'
  | 'health'
  | 'settings'


type Language = AppLanguage

export const dashboardTitles: Record<Language, Record<DashboardSection, string>> = {
  zh: {
    overview: '概览',
    memory: '共享记忆',
    tasks: '任务',
    radio: 'Agent Radio',
    dispatch: '调度',
    workflows: '工作流',
    analytics: '分析',
    backups: '备份',
    search: '搜索',
    tools: '工具',
    projects: '项目',
    health: '健康',
    settings: '设置'
  },
  en: {
    overview: 'Overview',
    memory: 'Memory',
    tasks: 'Tasks',
    radio: 'Agent Radio',
    dispatch: 'Dispatch',
    workflows: 'Workflows',
    analytics: 'Analytics',
    backups: 'Backups',
    search: 'Search',
    tools: 'Tools',
    projects: 'Projects',
    health: 'Health',
    settings: 'Settings'
  }
}

export const dashboardSubtitles: Record<Language, Record<DashboardSection, string>> = {
  zh: {
    overview: '多智能体协作工作台',
    memory: 'MEMORY.md 快照与待同步事件',
    tasks: '共享任务队列和执行状态',
    radio: '跨工具消息与审核请求',
    dispatch: '自动派发、重试和运行记录',
    workflows: 'Planner / Executor / Reviewer 协作链路',
    analytics: '记忆、任务、Radio 和 Relay 的趋势概览',
    backups: '备份集、文件浏览和恢复预览',
    search: '跨记忆、任务、Radio、工作流的全局检索',
    tools: '工具接入、能力注册表和运行状态',
    projects: '项目注册表与可见项目',
    health: '记忆、存储和运行健康检查',
    settings: 'Dashboard 运行偏好'
  },
  en: {
    overview: 'Local multi-agent collaboration status',
    memory: 'MEMORY.md snapshot and pending events',
    tasks: 'Shared task queue and execution state',
    radio: 'Cross-tool messages and review requests',
    dispatch: 'Automation dispatch, retries, and run records',
    workflows: 'Planner / executor / reviewer coordination',
    analytics: 'Memory, tasks, radio, and relay analytics',
    backups: 'Backup sets, file browser, and restore preview',
    search: 'Global search across memory, tasks, radio, and workflows',
    tools: 'Tool connectivity, capabilities, and runner health',
    projects: 'Project registry and visible projects',
    health: 'Memory, storage, and runtime diagnostics',
    settings: 'Dashboard runtime preferences'
  }
}

export const dashboardLabels = {
  zh: {
    refresh: '刷新',
    refreshing: '刷新中',
    language: 'English',
    connectionError: '无法连接本地 hub',
    noData: '暂无数据',
    overviewSystemActivity: '系统与活动',
    overviewCollaboration: '协作消息',
    overviewWork: '协作进展',
    overviewWorkDescription: '查看近期任务和工作流，快速了解团队正在推进的事项。',
    overviewSystem: '系统状态',
    overviewSystemDescription: '工具可用性与共享记忆的运行摘要。',
    overviewWorkflows: '最近工作流',
    overviewHealth: '健康摘要',
    overviewNoFailures: '最近没有失败记录。系统出现需要关注的问题时，会在这里显示。',
    overviewNoMessages: '尚无协作消息。Agent 开始交接或请求帮助后，最新消息会显示在这里。',
    overviewNoTasks: '还没有任务。创建或认领任务后，近期进展会显示在这里。',
    overviewNoWorkflows: '还没有工作流。新的协作流程启动后，会显示在这里。',
    overviewNoTools: '尚未检测到工具。刷新后，可用连接会显示在这里。',
    totalTasks: '任务总数',
    activeTasks: '活跃任务',
    workflows: '工作流',
    relayRate: 'Relay 成功率',
    toolsReady: '可自动执行工具',
    memoryRecords: '记忆记录',
    pendingEvents: '待同步事件',
    recentTasks: '任务队列',
    recentRadio: '最近消息',
    toolReadiness: '工具状态',
    toolInventory: '工具清单',
    toolName: '工具',
    toolDetail: '详情',
    recentFailures: '最近失败',
    status: '状态',
    project: '项目',
    owner: '负责人',
    title: '标题',
    type: '类型',
    updated: '更新时间',
    actions: '操作',
    from: '来自',
    to: '发往',
    message: '内容',
    workflowTitle: '工作流',
    role: '角色',
    mode: '模式',
    health: '健康',
    installed: '已安装',
    runnable: '可执行',
    configured: '已配置',
    capability: '能力',
    visibleProjects: '可见项目',
    unregisteredProjects: '未注册引用',
    theme: '主题',
    autoRefresh: '自动刷新',
    notifications: '通知',
    refreshInterval: '刷新间隔',
    memorySnapshot: '记忆快照',
    profile: '用户配置',
    dispatchThreads: 'Relay 线程',
    dispatchLogs: '运行日志',
    settingsPanel: '运行偏好',
    yes: '是',
    no: '否',
    syncInbox: '同步待处理事项',
    rebuildSnapshot: '更新状态',
    running: '执行中',
    recordMemory: '记录记忆',
    supersedeMemory: '修正记忆',
    memoryText: '记忆内容',
    kind: '类型',
    source: '来源',
    save: '保存',
    addTask: '新增任务',
    description: '描述',
    handoff: '交接',
    priority: '优先级',
    allProjects: '全部项目',
    allPriorities: '全部优先级',
    open: '待处理',
    active: '进行中',
    needsVerification: '待验证',
    completed: '已完成',
    statusLabels: {
      open: '待处理',
      claimed: '已认领',
      active: '进行中',
      in_progress: '进行中',
      needs_verification: '待验证',
      pending: '待处理',
      planned: '已计划',
      review: '待审核',
      blocked: '阻塞',
      failed: '失败',
      done: '已完成',
      completed: '已完成',
      cancelled: '已取消'
    },
    priorityLabels: {
      low: '低',
      normal: '普通',
      high: '高',
      urgent: '紧急'
    },
    claim: '认领',
    start: '开始',
    block: '阻塞',
    unblock: '解除阻塞',
    complete: '完成',
    completeDirectly: '直接完成',
    requestVerification: '请求验证',
    approveAndComplete: '验证通过并完成',
    reportIssue: '反馈问题',
    issueDescription: '问题描述',
    issueDescriptionPlaceholder: '描述功能不完整或存在的BUG...',
    reopenTask: '反馈后重新打开任务',
    reopen: '重开',
    cancelledTerminal: '此任务已取消并保持终态。',
    purge: '彻底删除',
    purgeTask: '物理删除任务',
    purgeConfirm: '确认删除',
    purgeWarning: '此操作将永久删除任务记录，无法撤销。请输入任务标题确认：',
    purgeSuccess: '任务已彻底删除',
    purgeFailed: '删除失败',
    purgeOnlyCancelled: '只能删除已取消的任务',
    approve: '通过',
    reject: '拒绝',
    addNote: '添加备注',
    moreActions: '更多操作',
    notePlaceholder: '备注或状态原因',
    broadcastMessage: '发送 Radio',
    sendRadioRequest: '发送 Radio 请求',
    reply: '回复',
    replyTo: '回复对象',
    thread: '线程',
    searchText: '搜索文本',
    allSenders: '全部发送方',
    allRecipients: '全部接收方',
    allTypes: '全部类型',
    promoteToMemory: '提升为记忆',
    triggerDispatch: '立即触发调度',
    forceDispatch: '强制执行',
    limit: '数量',
    model: '模型',
    modelPlaceholder: '可选，如 gpt-5.2',
    created: '创建时间',
    assignee: '执行人',
    notes: '备注',
    review: '审核',
    clear: '清除筛选',
    cancel: '取消',
    analyticsOverview: '分析概览',
    tasksByStatus: '任务状态分布',
    radioByType: 'Radio 类型分布',
    relayByState: 'Relay 状态分布',
    toolAutomation: '工具自动化',
    missing: '缺失',
    backupStorage: '备份存储',
    topProjects: '项目排行',
    globalSearch: '全局搜索',
    searchPlaceholder: '搜索记忆、任务、Radio 或工作流',
    resultCount: '结果数',
    elapsed: '耗时',
    range: '时间范围',
    sort: '排序',
    relevance: '相关性',
    newest: '最新',
    oldest: '最早',
    allRanges: '全部时间',
    last24h: '24 小时',
    last7d: '7 天',
    last30d: '30 天',
    last90d: '90 天',
    facets: '筛选维度',
    tags: '标签',
    results: '结果',
    score: '分数',
    backupSets: '备份集',
    storageUsed: '存储占用',
    retained: '保留',
    pruneCandidates: '可清理',
    createBackup: '创建备份',
    backupReason: '备份原因',
    inspectBackup: '查看文件',
    previewRestore: '恢复预览',
    backupFiles: '备份文件',
    restoreSummary: '恢复摘要',
    backupPolicy: '备份策略',
    githubBackup: 'GitHub 数据备份',
    githubEnabled: '启用 GitHub 备份',
    githubRemote: '远端仓库',
    githubRepoDir: '本地仓库目录',
    githubBranch: '分支',
    githubLastCommit: '最近提交',
    githubLastError: '最近错误',
    githubPlaintext: '明文敏感上传',
    githubSchedule: '计划任务',
    githubNextRun: '下次运行',
    githubDryRun: '预览上传风险',
    githubLocalRun: '创建本地完整备份',
    githubSave: '保存 GitHub 配置',
    githubAllowPlaintext: '允许明文敏感上传',
    githubWarning: '上传备份可能包含用户私有数据。上传前请确认远端仓库、访问权限、保留策略和恢复需要。',
    githubWouldBlock: '明文上传将被阻断',
    githubNoRemote: '未配置远端时只会创建本地备份',
    warnings: '提醒',
    files: '文件',
    issues: '风险项',
    upload: '上传',
    daily: '每日',
    weekly: '每周',
    preSync: '同步前',
    changed: '变化',
    different: '不同',
    missingCurrent: '当前缺失',
    unchanged: '未变化',
    bytes: '大小',
    path: '路径',
    manual: '手动',
    workflowTotal: '工作流总数',
    workflowActive: '活跃工作流',
    workflowReview: '待审核',
    workflowBlocked: '阻塞工作流',
    createWorkflow: '新建工作流',
    editWorkflow: '编辑工作流',
    deleteWorkflow: '删除工作流',
    allStatuses: '全部状态',
    planner: '规划者',
    executor: '执行者',
    reviewer: '审核者',
    observer: '观察者',
    workflowPlan: '计划',
    workflowAcceptance: '验收标准',
    workflowRisks: '风险',
    workflowLogs: '工作流日志',
    linkedItems: '关联项',
    startWorkflow: '开始',
    markReview: '提交审核',
    markDone: '标记完成',
    workflowResult: '执行结果',
    workflowNote: '备注',
    workflowSignal: '发送 Signal',
    viewExecutionGraph: '查看执行图',
    signalTo: '发送给',
    actionText: '内容',
    createdBy: '创建者',
    noMatches: '没有匹配结果',
    confirmDelete: '确认删除',
    confirmDeleteWorkflow: '删除后会从工作流列表移除，请确认只删除当前工作流。',
    refreshTools: '刷新工具',
    detectTools: '重新检测',
    refreshCapabilities: '刷新能力',
    manageConfig: '管理配置',
    installLocal: '写入本项目',
    installGlobal: '写入全局',
    localTarget: '本项目目标',
    globalTarget: '全局目标',
    rulePreview: '规则预览',
    previewUnavailable: '无可用预览',
    generatedAt: '生成时间',
    successRate: '成功率',
    avgRuntime: '平均耗时',
    lastRun: '最后运行',
    activeDispatches: '活跃调度',
    totalRuns: '运行次数',
    runner: 'Runner',
    command: '命令',
    healthReasons: '健康原因',
    declaredModels: '申报模型',
    availableModels: '可用模型',
    strengths: '擅长领域',
    toolFilterAll: '全部工具',
    toolFilterReady: '已就绪',
    toolFilterConnected: '已连接',
    toolFilterRunnable: '可运行',
    toolFilterMissing: '缺失',
    toolFilterNeeds: '需配置',
    capabilitySummary: '能力摘要',
    directCli: '直接 CLI',
    sharedState: '共享状态',
    autoDispatchLabel: '自动调度',
    snapshotLimit: '快照上限',
    coreLimit: '核心记忆上限',
    recentLimit: '近期记忆上限',
    lockStaleMs: '锁超时',
    languageSetting: '语言',
    lightMode: '浅色',
    darkMode: '深色',
    saveSettings: '保存设置',
    settingsSaved: '设置已保存',
    actionSucceeded: '操作已完成',
    actionFailed: '操作失败',
    pruneAfterSync: '同步后清理',
    repairSuggestions: '修复建议',
    healthScore: '健康分',
    totalRecords: '记录总数',
    duplicateRecords: '重复记录',
    corruptedRecords: '损坏记录',
    previewRepair: '预览修复',
    applyRepair: '应用修复',
    repairPlan: '修复计划',
    applied: '已应用',
    dryRun: '预览模式',
    confirmRepair: '该操作会修改本地记忆索引数据。请确认已查看修复计划。',
    duplicateGroups: '重复组',
    superseded: '将标记重复',
    settingsSyncSection: '同步与记忆',
    settingsDashboardSection: '仪表盘偏好',
    settingsBackupSection: '备份保留',
    memoryDir: '记忆目录',
    shortcuts: '快捷键',
    refreshSettings: '重载设置',
    invalidSettingsValue: '设置值必须是正整数',
    healthStatus: '健康状态',
    healthIssues: '健康问题',
    duplicateRate: '重复率',
    filesScanned: '扫描文件',
    includesChecked: '检查引用',
    duplicateExamples: '重复样例',
    corruptedExamples: '损坏样例',
    storageBreakdown: '存储明细',
    healthRawReport: '原始健康报告',
    noHealthIssues: '暂无健康问题',
    noHealthExamples: '暂无样例',
    refreshHealth: '刷新健康报告',
    repairLimit: '修复上限',
    totalActions: '总操作',
    ledgerRecordsUpdated: '更新记录',
    corruptedRecovered: '恢复损坏',
    corruptedArchived: '归档损坏',
    repairPreviewEmpty: '先点击预览修复生成计划',
    confirmApply: '确认应用'
  },
  en: {
    refresh: 'Refresh',
    refreshing: 'Refreshing',
    language: '中文',
    connectionError: 'Local hub is unreachable',
    noData: 'No data',
    overviewSystemActivity: 'System & activity',
    overviewCollaboration: 'Collaboration messages',
    overviewWork: 'Collaboration progress',
    overviewWorkDescription: 'Review recent tasks and workflows to see what the team is moving forward.',
    overviewSystem: 'System status',
    overviewSystemDescription: 'A running summary of tool readiness and shared memory.',
    overviewWorkflows: 'Recent workflows',
    overviewHealth: 'Health summary',
    overviewNoFailures: 'No recent failures. Issues that need attention will appear here.',
    overviewNoMessages: 'No collaboration messages yet. The latest handoffs and requests will appear here.',
    overviewNoTasks: 'No tasks yet. Recent progress will appear here after work is created or claimed.',
    overviewNoWorkflows: 'No workflows yet. New collaboration flows will appear here when they start.',
    overviewNoTools: 'No tools detected yet. Refresh to show available connections here.',
    totalTasks: 'Total tasks',
    activeTasks: 'Active tasks',
    workflows: 'Workflows',
    relayRate: 'Relay success',
    toolsReady: 'Automated tools',
    memoryRecords: 'Memory records',
    pendingEvents: 'Pending events',
    recentTasks: 'Task queue',
    recentRadio: 'Recent radio',
    toolReadiness: 'Tool readiness',
    toolInventory: 'Tool inventory',
    toolName: 'Tool',
    toolDetail: 'Detail',
    recentFailures: 'Recent failures',
    status: 'Status',
    project: 'Project',
    owner: 'Owner',
    title: 'Title',
    type: 'Type',
    updated: 'Updated',
    actions: 'Actions',
    from: 'From',
    to: 'To',
    message: 'Message',
    workflowTitle: 'Workflow',
    role: 'Role',
    mode: 'Mode',
    health: 'Health',
    installed: 'Installed',
    runnable: 'Runnable',
    configured: 'Configured',
    capability: 'Capability',
    visibleProjects: 'Visible projects',
    unregisteredProjects: 'Unregistered refs',
    theme: 'Theme',
    autoRefresh: 'Auto refresh',
    notifications: 'Notifications',
    refreshInterval: 'Refresh interval',
    memorySnapshot: 'Memory snapshot',
    profile: 'Profile',
    dispatchThreads: 'Relay threads',
    dispatchLogs: 'Run logs',
    settingsPanel: 'Runtime preferences',
    yes: 'Yes',
    no: 'No',
    syncInbox: 'Sync Inbox',
    rebuildSnapshot: 'Rebuild Snapshot',
    running: 'Running',
    recordMemory: 'Record memory',
    supersedeMemory: 'Supersede memory',
    memoryText: 'Memory text',
    kind: 'Kind',
    source: 'Source',
    save: 'Save',
    addTask: 'Add task',
    description: 'Description',
    handoff: 'Handoff',
    priority: 'Priority',
    allProjects: 'All projects',
    allPriorities: 'All priorities',
    open: 'Open',
    active: 'Active',
    needsVerification: 'Needs Verification',
    completed: 'Completed',
    statusLabels: {
      open: 'Open',
      claimed: 'Claimed',
      active: 'Active',
      in_progress: 'In progress',
      needs_verification: 'Needs verification',
      pending: 'Pending',
      planned: 'Planned',
      review: 'In review',
      blocked: 'Blocked',
      failed: 'Failed',
      done: 'Done',
      completed: 'Completed',
      cancelled: 'Cancelled'
    },
    priorityLabels: {
      low: 'Low',
      normal: 'Normal',
      high: 'High',
      urgent: 'Urgent'
    },
    claim: 'Claim',
    start: 'Start',
    block: 'Block',
    unblock: 'Unblock',
    complete: 'Complete',
    completeDirectly: 'Complete Directly',
    requestVerification: 'Request Verification',
    approveAndComplete: 'Approve & Complete',
    reportIssue: 'Report Issue',
    issueDescription: 'Issue Description',
    issueDescriptionPlaceholder: 'Describe what is incomplete or buggy...',
    reopenTask: 'Reopen task after reporting',
    reopen: 'Reopen',
    cancelledTerminal: 'This task is cancelled and remains terminal.',
    purge: 'Purge',
    purgeTask: 'Permanently delete task',
    purgeConfirm: 'Confirm deletion',
    purgeWarning: 'This action will permanently delete the task record and cannot be undone. Enter the task title to confirm:',
    purgeSuccess: 'Task purged successfully',
    purgeFailed: 'Purge failed',
    purgeOnlyCancelled: 'Only cancelled tasks can be purged',
    approve: 'Approve',
    reject: 'Reject',
    addNote: 'Add note',
    moreActions: 'More actions',
    notePlaceholder: 'Note or status reason',
    broadcastMessage: 'Send radio',
    sendRadioRequest: 'Send radio request',
    reply: 'Reply',
    replyTo: 'Reply to',
    thread: 'Thread',
    searchText: 'Search text',
    allSenders: 'All senders',
    allRecipients: 'All recipients',
    allTypes: 'All types',
    promoteToMemory: 'Promote to memory',
    triggerDispatch: 'Trigger dispatch',
    forceDispatch: 'Force run',
    limit: 'Limit',
    model: 'Model',
    modelPlaceholder: 'Optional, e.g. gpt-5.2',
    created: 'Created',
    assignee: 'Assignee',
    notes: 'Notes',
    review: 'Review',
    clear: 'Clear filters',
    cancel: 'Cancel',
    analyticsOverview: 'Analytics overview',
    tasksByStatus: 'Tasks by status',
    radioByType: 'Radio by type',
    relayByState: 'Relay by state',
    toolAutomation: 'Tool automation',
    missing: 'Missing',
    backupStorage: 'Backup storage',
    topProjects: 'Top projects',
    globalSearch: 'Global search',
    searchPlaceholder: 'Search memories, tasks, radio, or workflows',
    resultCount: 'Results',
    elapsed: 'Elapsed',
    range: 'Range',
    sort: 'Sort',
    relevance: 'Relevance',
    newest: 'Newest',
    oldest: 'Oldest',
    allRanges: 'All time',
    last24h: '24 hours',
    last7d: '7 days',
    last30d: '30 days',
    last90d: '90 days',
    facets: 'Facets',
    tags: 'Tags',
    results: 'Results',
    score: 'Score',
    backupSets: 'Backup sets',
    storageUsed: 'Storage used',
    retained: 'Retained',
    pruneCandidates: 'Prune candidates',
    createBackup: 'Create backup',
    backupReason: 'Backup reason',
    inspectBackup: 'Inspect files',
    previewRestore: 'Restore preview',
    backupFiles: 'Backup files',
    restoreSummary: 'Restore summary',
    backupPolicy: 'Backup policy',
    githubBackup: 'GitHub data backup',
    githubEnabled: 'Enable GitHub backup',
    githubRemote: 'Remote repository',
    githubRepoDir: 'Local repo directory',
    githubBranch: 'Branch',
    githubLastCommit: 'Last commit',
    githubLastError: 'Last error',
    githubPlaintext: 'Plaintext sensitive upload',
    githubSchedule: 'Schedule',
    githubNextRun: 'Next run',
    githubDryRun: 'Preview upload risk',
    githubLocalRun: 'Create local full backup',
    githubSave: 'Save GitHub config',
    githubAllowPlaintext: 'Allow plaintext sensitive upload',
    githubWarning: 'Backup uploads can include private user data. Verify the remote, access controls, retention policy, and recovery need before uploading.',
    githubWouldBlock: 'Plaintext upload would be blocked',
    githubNoRemote: 'Without a remote, only local backup is created',
    warnings: 'Warnings',
    files: 'Files',
    issues: 'Issues',
    upload: 'Upload',
    daily: 'Daily',
    weekly: 'Weekly',
    preSync: 'Pre-sync',
    changed: 'Changed',
    different: 'Different',
    missingCurrent: 'Missing current',
    unchanged: 'Unchanged',
    bytes: 'Bytes',
    path: 'Path',
    manual: 'Manual',
    workflowTotal: 'Total workflows',
    workflowActive: 'Active workflows',
    workflowReview: 'In review',
    workflowBlocked: 'Blocked workflows',
    createWorkflow: 'Create workflow',
    editWorkflow: 'Edit workflow',
    deleteWorkflow: 'Delete workflow',
    allStatuses: 'All statuses',
    planner: 'Planner',
    executor: 'Executor',
    reviewer: 'Reviewer',
    observer: 'Observer',
    workflowPlan: 'Plan',
    workflowAcceptance: 'Acceptance',
    workflowRisks: 'Risks',
    workflowLogs: 'Workflow logs',
    linkedItems: 'Linked items',
    startWorkflow: 'Start',
    markReview: 'Send to review',
    markDone: 'Mark done',
    workflowResult: 'Result',
    workflowNote: 'Note',
    workflowSignal: 'Send signal',
    viewExecutionGraph: 'View execution graph',
    signalTo: 'Send to',
    actionText: 'Text',
    createdBy: 'Created by',
    noMatches: 'No matches',
    confirmDelete: 'Confirm delete',
    confirmDeleteWorkflow: 'This removes the workflow from the list. Confirm that only this workflow should be deleted.',
    refreshTools: 'Refresh tools',
    detectTools: 'Detect again',
    refreshCapabilities: 'Refresh capabilities',
    manageConfig: 'Manage config',
    installLocal: 'Write project',
    installGlobal: 'Write global',
    localTarget: 'Project target',
    globalTarget: 'Global target',
    rulePreview: 'Rule preview',
    previewUnavailable: 'No preview available',
    generatedAt: 'Generated at',
    successRate: 'Success rate',
    avgRuntime: 'Avg runtime',
    lastRun: 'Last run',
    activeDispatches: 'Active dispatches',
    totalRuns: 'Runs',
    runner: 'Runner',
    command: 'Command',
    healthReasons: 'Health reasons',
    declaredModels: 'Declared models',
    availableModels: 'Available models',
    strengths: 'Strengths',
    toolFilterAll: 'All tools',
    toolFilterReady: 'Ready',
    toolFilterConnected: 'Connected',
    toolFilterRunnable: 'Runnable',
    toolFilterMissing: 'Missing',
    toolFilterNeeds: 'Needs config',
    capabilitySummary: 'Capability summary',
    directCli: 'Direct CLI',
    sharedState: 'Shared state',
    autoDispatchLabel: 'Auto dispatch',
    snapshotLimit: 'Snapshot limit',
    coreLimit: 'Core limit',
    recentLimit: 'Recent limit',
    lockStaleMs: 'Lock timeout',
    languageSetting: 'Language',
    lightMode: 'Light',
    darkMode: 'Dark',
    saveSettings: 'Save settings',
    settingsSaved: 'Settings saved',
    actionSucceeded: 'Action completed',
    actionFailed: 'Action failed',
    pruneAfterSync: 'Prune after sync',
    repairSuggestions: 'Repair suggestions',
    healthScore: 'Health score',
    totalRecords: 'Total records',
    duplicateRecords: 'Duplicate records',
    corruptedRecords: 'Corrupted records',
    previewRepair: 'Preview repair',
    applyRepair: 'Apply repair',
    repairPlan: 'Repair plan',
    applied: 'Applied',
    dryRun: 'Dry run',
    confirmRepair: 'This operation changes local memory index data. Confirm that you reviewed the repair plan.',
    duplicateGroups: 'Duplicate groups',
    superseded: 'To supersede',
    settingsSyncSection: 'Sync and memory',
    settingsDashboardSection: 'Dashboard preferences',
    settingsBackupSection: 'Backup retention',
    memoryDir: 'Memory directory',
    shortcuts: 'Shortcuts',
    refreshSettings: 'Reload settings',
    invalidSettingsValue: 'Settings values must be positive integers',
    healthStatus: 'Health status',
    healthIssues: 'Health issues',
    duplicateRate: 'Duplicate rate',
    filesScanned: 'Files scanned',
    includesChecked: 'Includes checked',
    duplicateExamples: 'Duplicate examples',
    corruptedExamples: 'Corrupted examples',
    storageBreakdown: 'Storage breakdown',
    healthRawReport: 'Raw health report',
    noHealthIssues: 'No health issues',
    noHealthExamples: 'No examples',
    refreshHealth: 'Refresh health',
    repairLimit: 'Repair limit',
    totalActions: 'Total actions',
    ledgerRecordsUpdated: 'Updated records',
    corruptedRecovered: 'Recovered corrupted',
    corruptedArchived: 'Archived corrupted',
    repairPreviewEmpty: 'Preview repair first to generate a plan',
    confirmApply: 'Confirm apply'
  }
}

export type DashboardCopy = typeof dashboardLabels.zh
