import type { AppLanguage } from './i18n'

export type DashboardSection =
  | 'overview'
  | 'memory'
  | 'tasks'
  | 'radio'
  | 'dispatch'
  | 'workflows'
  | 'analytics'
  | 'backups'
  | 'search'
  | 'tools'
  | 'projects'
  | 'health'
  | 'settings'


type Language = AppLanguage

export const dashboardTitles: Record<Language, Record<DashboardSection, string>> = {
  zh: {
    overview: '概览',
    memory: '共享记忆',
    tasks: '任务',
    radio: 'Agent Radio',
    dispatch: '调度',
    workflows: '工作流',
    analytics: '分析',
    backups: '备份',
    search: '搜索',
    tools: '工具',
    projects: '项目',
    health: '健康',
    settings: '设置'
  },
  en: {
    overview: 'Overview',
    memory: 'Memory',
    tasks: 'Tasks',
    radio: 'Agent Radio',
    dispatch: 'Dispatch',
    workflows: 'Workflows',
    analytics: 'Analytics',
    backups: 'Backups',
    search: 'Search',
    tools: 'Tools',
    projects: 'Projects',
    health: 'Health',
    settings: 'Settings'
  }
}

export const dashboardSubtitles: Record<Language, Record<DashboardSection, string>> = {
  zh: {
    overview: '多智能体协作工作台',
    memory: 'MEMORY.md 快照与待同步事件',
    tasks: '共享任务队列和执行状态',
    radio: '跨工具消息与审核请求',
    dispatch: '自动派发、重试和运行记录',
    workflows: 'Planner / Executor / Reviewer 协作链路',
    analytics: '记忆、任务、Radio 和 Relay 的趋势概览',
    backups: '备份集、文件浏览和恢复预览',
    search: '跨记忆、任务、Radio、工作流的全局检索',
    tools: '工具接入、能力注册表和运行状态',
    projects: '项目注册表与可见项目',
    health: '记忆、存储和运行健康检查',
    settings: 'Dashboard 运行偏好'
  },
  en: {
    overview: 'Local multi-agent collaboration status',
    memory: 'MEMORY.md snapshot and pending events',
    tasks: 'Shared task queue and execution state',
    radio: 'Cross-tool messages and review requests',
    dispatch: 'Automation dispatch, retries, and run records',
    workflows: 'Planner / executor / reviewer coordination',
    analytics: 'Memory, tasks, radio, and relay analytics',
    backups: 'Backup sets, file browser, and restore preview',
    search: 'Global search across memory, tasks, radio, and workflows',
    tools: 'Tool connectivity, capabilities, and runner health',
    projects: 'Project registry and visible projects',
    health: 'Memory, storage, and runtime diagnostics',
    settings: 'Dashboard runtime preferences'
  }
}

const labels = {
  zh: {
    refresh: '刷新',
    refreshing: '刷新中',
    language: 'English',
    connectionError: '无法连接本地 hub',
    noData: '暂无数据',
    overviewSystemActivity: '系统与活动',
    overviewCollaboration: '协作消息',
    overviewWork: '协作进展',
    overviewWorkDescription: '查看近期任务和工作流，快速了解团队正在推进的事项。',
    overviewSystem: '系统状态',
    overviewSystemDescription: '工具可用性与共享记忆的运行摘要。',
    overviewWorkflows: '最近工作流',
    overviewHealth: '健康摘要',
    overviewNoFailures: '最近没有失败记录。系统出现需要关注的问题时，会在这里显示。',
    overviewNoMessages: '尚无协作消息。Agent 开始交接或请求帮助后，最新消息会显示在这里。',
    overviewNoTasks: '还没有任务。创建或认领任务后，近期进展会显示在这里。',
    overviewNoWorkflows: '还没有工作流。新的协作流程启动后，会显示在这里。',
    overviewNoTools: '尚未检测到工具。刷新后，可用连接会显示在这里。',
    totalTasks: '任务总数',
    activeTasks: '活跃任务',
    workflows: '工作流',
    relayRate: 'Relay 成功率',
    toolsReady: '可自动执行工具',
    memoryRecords: '记忆记录',
    pendingEvents: '待同步事件',
    recentTasks: '任务队列',
    recentRadio: '最近消息',
    toolReadiness: '工具状态',
    toolInventory: '工具清单',
    toolName: '工具',
    toolDetail: '详情',
    recentFailures: '最近失败',
    status: '状态',
    project: '项目',
    owner: '负责人',
    title: '标题',
    type: '类型',
    updated: '更新时间',
    actions: '操作',
    from: '来自',
    to: '发往',
    message: '内容',
    workflowTitle: '工作流',
    role: '角色',
    mode: '模式',
    health: '健康',
    installed: '已安装',
    runnable: '可执行',
    configured: '已配置',
    capability: '能力',
    visibleProjects: '可见项目',
    unregisteredProjects: '未注册引用',
    theme: '主题',
    autoRefresh: '自动刷新',
    notifications: '通知',
    refreshInterval: '刷新间隔',
    memorySnapshot: '记忆快照',
    profile: '用户配置',
    dispatchThreads: 'Relay 线程',
    dispatchLogs: '运行日志',
    settingsPanel: '运行偏好',
    yes: '是',
    no: '否',
    syncInbox: '同步待处理事项',
    rebuildSnapshot: '更新状态',
    running: '执行中',
    recordMemory: '记录记忆',
    supersedeMemory: '修正记忆',
    memoryText: '记忆内容',
    kind: '类型',
    source: '来源',
    save: '保存',
    addTask: '新增任务',
    description: '描述',
    handoff: '交接',
    priority: '优先级',
    allProjects: '全部项目',
    allPriorities: '全部优先级',
    open: '待处理',
    active: '进行中',
    needsVerification: '待验证',
    completed: '已完成',
    statusLabels: {
      open: '待处理',
      claimed: '已认领',
      active: '进行中',
      in_progress: '进行中',
      needs_verification: '待验证',
      pending: '待处理',
      planned: '已计划',
      review: '待审核',
      blocked: '阻塞',
      failed: '失败',
      done: '已完成',
      completed: '已完成',
      cancelled: '已取消',
      connected: '已连接',
      ready: '就绪',
      missing: '缺失',
      error: '错误',
      note: '备注',
      request: '请求',
      response: '回复',
      handoff: '交接'
    },
    priorityLabels: {
      low: '低',
      normal: '普通',
      high: '高',
      urgent: '紧急'
    },
    claim: '认领',
    start: '开始',
    block: '阻塞',
    unblock: '解除阻塞',
    complete: '完成',
    completeDirectly: '直接完成',
    requestVerification: '请求验证',
    approveAndComplete: '验证通过并完成',
    reportIssue: '反馈问题',
    issueDescription: '问题描述',
    issueDescriptionPlaceholder: '描述功能不完整或存在的BUG...',
    reopenTask: '反馈后重新打开任务',
    reopen: '重开',
    cancelledTerminal: '此任务已取消并保持终态。',
    purge: '彻底删除',
    purgeTask: '物理删除任务',
    purgeConfirm: '确认删除',
    purgeWarning: '此操作将永久删除任务记录，无法撤销。请输入任务标题确认：',
    purgeSuccess: '任务已彻底删除',
    purgeFailed: '删除失败',
    purgeOnlyCancelled: '只能删除已取消的任务',
    approve: '通过',
    reject: '拒绝',
    addNote: '添加备注',
    moreActions: '更多操作',
    notePlaceholder: '备注或状态原因',
    broadcastMessage: '发送 Radio',
    sendRadioRequest: '发送 Radio 请求',
    reply: '回复',
    replyTo: '回复对象',
    thread: '线程',
    searchText: '搜索文本',
    allSenders: '全部发送方',
    allRecipients: '全部接收方',
    allTypes: '全部类型',
    promoteToMemory: '提升为记忆',
    triggerDispatch: '立即触发调度',
    forceDispatch: '强制执行',
    limit: '数量',
    model: '模型',
    modelPlaceholder: '可选，如 gpt-5.2',
    created: '创建时间',
    assignee: '执行人',
    notes: '备注',
    review: '审核',
    clear: '清除筛选',
    cancel: '取消',
    analyticsOverview: '分析概览',
    tasksByStatus: '任务状态分布',
    radioByType: 'Radio 类型分布',
    relayByState: 'Relay 状态分布',
    toolAutomation: '工具自动化',
    missing: '缺失',
    backupStorage: '备份存储',
    topProjects: '项目排行',
    globalSearch: '全局搜索',
    searchPlaceholder: '搜索记忆、任务、Radio 或工作流',
    resultCount: '结果数',
    elapsed: '耗时',
    range: '时间范围',
    sort: '排序',
    relevance: '相关性',
    newest: '最新',
    oldest: '最早',
    allRanges: '全部时间',
    last24h: '24 小时',
    last7d: '7 天',
    last30d: '30 天',
    last90d: '90 天',
    facets: '筛选维度',
    tags: '标签',
    results: '结果',
    score: '分数',
    backupSets: '备份集',
    storageUsed: '存储占用',
    retained: '保留',
    pruneCandidates: '可清理',
    createBackup: '创建备份',
    backupReason: '备份原因',
    inspectBackup: '查看文件',
    previewRestore: '恢复预览',
    backupFiles: '备份文件',
    restoreSummary: '恢复摘要',
    backupPolicy: '备份策略',
    githubBackup: 'GitHub 数据备份',
    githubEnabled: '启用 GitHub 备份',
    githubRemote: '远端仓库',
    githubRepoDir: '本地仓库目录',
    githubBranch: '分支',
    githubLastCommit: '最近提交',
    githubLastError: '最近错误',
    githubPlaintext: '明文敏感上传',
    githubSchedule: '计划任务',
    githubNextRun: '下次运行',
    githubDryRun: '预览上传风险',
    githubLocalRun: '创建本地完整备份',
    githubSave: '保存 GitHub 配置',
    githubAllowPlaintext: '允许明文敏感上传',
    githubWarning: '上传备份可能包含用户私有数据。上传前请确认远端仓库、访问权限、保留策略和恢复需要。',
    githubWouldBlock: '明文上传将被阻断',
    githubNoRemote: '未配置远端时只会创建本地备份',
    warnings: '提醒',
    files: '文件',
    issues: '风险项',
    upload: '上传',
    daily: '每日',
    weekly: '每周',
    preSync: '同步前',
    changed: '变化',
    different: '不同',
    missingCurrent: '当前缺失',
    unchanged: '未变化',
    bytes: '大小',
    path: '路径',
    manual: '手动',
    workflowTotal: '工作流总数',
    workflowActive: '活跃工作流',
    workflowReview: '待审核',
    workflowBlocked: '阻塞工作流',
    createWorkflow: '新建工作流',
    editWorkflow: '编辑工作流',
    deleteWorkflow: '删除工作流',
    allStatuses: '全部状态',
    planner: '规划者',
    executor: '执行者',
    reviewer: '审核者',
    observer: '观察者',
    workflowPlan: '计划',
    workflowAcceptance: '验收标准',
    workflowRisks: '风险',
    workflowLogs: '工作流日志',
    linkedItems: '关联项',
    startWorkflow: '开始',
    markReview: '提交审核',
    markDone: '标记完成',
    workflowResult: '执行结果',
    workflowNote: '备注',
    workflowReviewEntry: '审核意见',
    workflowSignal: '发送 Signal',
    viewExecutionGraph: '查看执行图',
    signalTo: '发送给',
    signalToPlaceholder: '接收方，例如 reviewer 或 all',
    actionText: '内容',
    actionTextPlaceholder: '输入内容…',
    workflowTitleRequired: '请输入工作流标题',
    workflowTextRequired: '请输入内容',
    workflowSignalTargetRequired: '请输入接收方',
    createdBy: '创建者',
    noMatches: '没有匹配结果',
    confirmDelete: '确认删除',
    confirmDeleteWorkflow: '删除后会从工作流列表移除，请确认只删除当前工作流。',
    refreshTools: '刷新工具',
    detectTools: '重新检测',
    refreshCapabilities: '刷新能力',
    manageConfig: '管理配置',
    installLocal: '写入本项目',
    installGlobal: '写入全局',
    localTarget: '本项目目标',
    globalTarget: '全局目标',
    rulePreview: '规则预览',
    previewUnavailable: '无可用预览',
    generatedAt: '生成时间',
    successRate: '成功率',
    avgRuntime: '平均耗时',
    lastRun: '最后运行',
    activeDispatches: '活跃调度',
    totalRuns: '运行次数',
    runner: 'Runner',
    command: '命令',
    healthReasons: '健康原因',
    declaredModels: '申报模型',
    availableModels: '可用模型',
    strengths: '擅长领域',
    toolFilterAll: '全部工具',
    toolFilterReady: '已就绪',
    toolFilterConnected: '已连接',
    toolFilterRunnable: '可运行',
    toolFilterMissing: '缺失',
    toolFilterNeeds: '需配置',
    capabilitySummary: '能力摘要',
    directCli: '直接 CLI',
    sharedState: '共享状态',
    autoDispatchLabel: '自动调度',
    snapshotLimit: '快照上限',
    coreLimit: '核心记忆上限',
    recentLimit: '近期记忆上限',
    lockStaleMs: '锁超时',
    languageSetting: '语言',
    lightMode: '浅色',
    darkMode: '深色',
    saveSettings: '保存设置',
    settingsSaved: '设置已保存',
    actionSucceeded: '操作已完成',
    actionFailed: '操作失败',
    pruneAfterSync: '同步后清理',
    repairSuggestions: '修复建议',
    healthScore: '健康分',
    totalRecords: '记录总数',
    duplicateRecords: '重复记录',
    corruptedRecords: '损坏记录',
    previewRepair: '预览修复',
    applyRepair: '应用修复',
    repairPlan: '修复计划',
    applied: '已应用',
    dryRun: '预览模式',
    confirmRepair: '该操作会修改本地记忆索引数据。请确认已查看修复计划。',
    duplicateGroups: '重复组',
    superseded: '将标记重复',
    settingsSyncSection: '同步与记忆',
    settingsDashboardSection: '仪表盘偏好',
    settingsBackupSection: '备份保留',
    memoryDir: '记忆目录',
    shortcuts: '快捷键',
    refreshSettings: '重载设置',
    invalidSettingsValue: '设置值必须是正整数',
    healthStatus: '健康状态',
    healthIssues: '健康问题',
    duplicateRate: '重复率',
    filesScanned: '扫描文件',
    includesChecked: '检查引用',
    duplicateExamples: '重复样例',
    corruptedExamples: '损坏样例',
    storageBreakdown: '存储明细',
    healthRawReport: '原始健康报告',
    noHealthIssues: '暂无健康问题',
    noHealthExamples: '暂无样例',
    refreshHealth: '刷新健康报告',
    repairLimit: '修复上限',
    totalActions: '总操作',
    ledgerRecordsUpdated: '更新记录',
    corruptedRecovered: '恢复损坏',
    corruptedArchived: '归档损坏',
    repairPreviewEmpty: '先点击预览修复生成计划',
    confirmApply: '确认应用',
    // Status badge variants (connection + message types)
    connected: '已连接',
    ready: '就绪',
    error: '错误',
    note: '备注',
    request: '请求',
    response: '回复',
    handoffBadge: '交接',
    projectStatusLabels: {
      active: '活跃',
      paused: '暂停',
      archived: '归档',
      hidden: '隐藏'
    },
    allOption: '全部',
    // Memory panel + related entities
    memoryOverview: '记忆总览',
    close: '关闭',
    relationContext: '关联上下文',
    id: 'ID',
    time: '时间',
    confirmedRelations: '已确认关联',
    inferredContext: '自动推断上下文',
    inferredNone: '暂无自动推断',
    noRelations: '暂无',
    contentContext: '内容上下文',
    loadingRelations: '读取关联中…',
    // Lists / counts
    messageCount: '条消息',
    workflowCount: '条工作流',
    itemsSelected: '项已选',
    noMatchesProject: '没有匹配的项目',
    messagePlaceholder: '输入消息内容…',
    titlePlaceholder: '输入工作流标题',
    searchProjectPlaceholder: '搜索项目',
    // Tasks detail dialog
    executionInfo: '执行信息',
    deliveryState: '交付状态',
    attempts: '执行次数',
    progressLabel: '进度',
    reviewStatusLabel: '审核状态',
    recentIssue: '最近问题',
    activityLog: '活动记录',
    taskLabel: '任务',
    worktreeLabel: '工作树',
    // Projects edit dialog
    projectStatusLabel: '状态',
    nameLabel: '名称',
    displayNameLabel: '显示名称',
    typeLabel: '类型',
    descriptionLabel: '描述',
    aliasesLabel: '别名（逗号分隔）',
    metadataLabel: '元数据（JSON）',
    resourcesLabel: '资源（JSON）',
    editProject: '编辑项目',
    saving: '保存中…',
    invalidMetadataJson: '元数据 JSON 无效',
    invalidResourcesJson: '资源 JSON 无效',
    createdLabel: '创建时间',
    updatedLabel: '更新时间',
    repo: '仓库',
    feishu: '飞书',
    archive: '归档',
    // Agent execution panel
    agentExecutionCenter: 'Agent 执行中心',
    executionCockpit: '执行舱',
    whatAgentsDoing: 'Agent 正在做什么',
    sessionsLabel: '个会话',
    needsAttention: '待处理',
    reviewsLabel: '个审查',
    markRead: '标为已读',
    noAgentSessions: '暂无 Agent 会话，等待 dispatch 或 heartbeat。',
    unifiedTimeline: '统一时间线',
    noActivity: '暂无活动事件。',
    worktreeReview: '工作树审查',
    readyForReview: '可审查',
    noWorktrees: '暂无工作树。',
    sessionStateLabels: {
      working: '工作中',
      idle: '空闲',
      blocked: '阻塞',
      waiting_review: '待审查',
      done: '完成',
      failed: '失败',
      stale: '已过期'
    },
    // Credentials
    credentialId: '凭据 ID',
    credentialSecret: '密钥（保存后隐藏）',
    credentialEnv: '或环境变量名',
    // Chat
    chat: {
      title: '对话',
      language: 'English',
      empty: '暂无消息',
      placeholder: '输入消息',
      send: '发送',
      sending: '发送中',
      to: '发往',
      project: '项目',
      toolsUnavailable: '暂无可选工具',
      loadingTools: '正在加载可用工具…'
    },
    skills: {
      title: '共享 Skill 中心',
      subtitle: '统一安装一次，多个项目和 Agent 共用。',
      syncTargets: '同步目标',
      refreshStatus: '刷新状态',
      syncToAgents: '同步到 Agent',
      registrySkills: 'Registry Skill',
      enabledHere: '当前项目已启用',
      discoveredLocally: '本机发现',
      conflicts: '冲突',
      targetVariants: '适配变体',
      protectedCore: '受保护核心',
      canonicalRegistry: '统一 Skill Registry',
      searchPlaceholder: '搜索 Skill',
      projectionNote: 'Agent 目录只保留受管入口，不再作为源文件',
      versions: '个版本',
      notSelected: '未选择',
      updateAvailable: '有更新',
      enabled: '已启用',
      disabled: '未启用',
      relations: '关联',
      enable: '启用',
      disable: '停用',
      emptyImported: '还没有导入 Skill。可从下方本机发现列表导入。',
      localDiscovery: '本机 Skill 发现',
      coreAdapterProtected: 'AMH 核心适配器，禁止导入',
      targetVariantsNote: 'Agent 目标适配变体，按目标查看',
      contentConflict: '内容冲突，请选择版本',
      duplicateMerged: '重复来源已合并',
      readyToImport: '待导入',
      sources: '个来源',
      viewRelations: '查看关联',
      protected: '受保护',
      targetVariantBadge: '目标变体',
      chooseVersion: '需选择',
      deduplicated: '已去重',
      importSelected: '导入所选版本',
      importToAmh: '导入到 AMH',
      sharedCredentials: '统一凭据',
      credentialNote: '凭据只配置一次，密钥不会返回到页面或 Skill 文件。',
      noCredentials: '尚未配置凭据'
    },
    extensions: {
      title: 'MCP 同步中心',
      subtitle: '管理 MCP 服务器配置，同步到 Claude、Codex、Gemini、OpenCode。Skill 请前往 Skills 页面管理。',
      refresh: '刷新',
      importAll: '导入全部',
      diff: '查看差异',
      registryMcp: '注册 MCP',
      skillManagement: 'Skill 管理',
      openSkillsPage: '前往 Skills 页面',
      managed: '受管扩展',
      syncedExtensions: '已同步扩展',
      conflicts: '冲突',
      searchPlaceholder: '搜索扩展',
      all: '全部',
      applyElsePreview: '应用（否则仅预览）',
      applySync: '应用同步',
      previewSync: '预览同步',
      diffPreview: '差异预览',
      toAdd: '待添加',
      current: '一致',
      currentBadge: '一致',
      add: '添加',
      conflict: '冲突',
      noDifferences: '没有差异',
      remove: '移除',
      removeFromList: '从注册表移除',
      removeQuestion: '确定移除？',
      confirmYes: '确定',
      confirmNo: '取消',
      unmanaged: '未受管',
      detected: '已检测',
      notDetected: '未检测',
      mcp: 'MCP',
      skillKind: 'Skill',
      changes: '项变更',
      applied: '已应用',
      previewOnly: '仅预览',
      syncApplied: '同步已应用',
      previewComplete: '预览完成，未修改文件',
      emptySynced: '还没有同步扩展。可点击“导入全部”读取现有 MCP，Skill 请在 Skills 页面管理。'
    }
  },
  en: {
    refresh: 'Refresh',
    refreshing: 'Refreshing',
    language: '中文',
    connectionError: 'Local hub is unreachable',
    noData: 'No data',
    overviewSystemActivity: 'System & activity',
    overviewCollaboration: 'Collaboration messages',
    overviewWork: 'Collaboration progress',
    overviewWorkDescription: 'Review recent tasks and workflows to see what the team is moving forward.',
    overviewSystem: 'System status',
    overviewSystemDescription: 'A running summary of tool readiness and shared memory.',
    overviewWorkflows: 'Recent workflows',
    overviewHealth: 'Health summary',
    overviewNoFailures: 'No recent failures. Issues that need attention will appear here.',
    overviewNoMessages: 'No collaboration messages yet. The latest handoffs and requests will appear here.',
    overviewNoTasks: 'No tasks yet. Recent progress will appear here after work is created or claimed.',
    overviewNoWorkflows: 'No workflows yet. New collaboration flows will appear here when they start.',
    overviewNoTools: 'No tools detected yet. Refresh to show available connections here.',
    totalTasks: 'Total tasks',
    activeTasks: 'Active tasks',
    workflows: 'Workflows',
    relayRate: 'Relay success',
    toolsReady: 'Automated tools',
    memoryRecords: 'Memory records',
    pendingEvents: 'Pending events',
    recentTasks: 'Task queue',
    recentRadio: 'Recent radio',
    toolReadiness: 'Tool readiness',
    toolInventory: 'Tool inventory',
    toolName: 'Tool',
    toolDetail: 'Detail',
    recentFailures: 'Recent failures',
    status: 'Status',
    project: 'Project',
    owner: 'Owner',
    title: 'Title',
    type: 'Type',
    updated: 'Updated',
    actions: 'Actions',
    from: 'From',
    to: 'To',
    message: 'Message',
    workflowTitle: 'Workflow',
    role: 'Role',
    mode: 'Mode',
    health: 'Health',
    installed: 'Installed',
    runnable: 'Runnable',
    configured: 'Configured',
    capability: 'Capability',
    visibleProjects: 'Visible projects',
    unregisteredProjects: 'Unregistered refs',
    theme: 'Theme',
    autoRefresh: 'Auto refresh',
    notifications: 'Notifications',
    refreshInterval: 'Refresh interval',
    memorySnapshot: 'Memory snapshot',
    profile: 'Profile',
    dispatchThreads: 'Relay threads',
    dispatchLogs: 'Run logs',
    settingsPanel: 'Runtime preferences',
    yes: 'Yes',
    no: 'No',
    syncInbox: 'Sync Inbox',
    rebuildSnapshot: 'Rebuild Snapshot',
    running: 'Running',
    recordMemory: 'Record memory',
    supersedeMemory: 'Supersede memory',
    memoryText: 'Memory text',
    kind: 'Kind',
    source: 'Source',
    save: 'Save',
    addTask: 'Add task',
    description: 'Description',
    handoff: 'Handoff',
    priority: 'Priority',
    allProjects: 'All projects',
    allPriorities: 'All priorities',
    open: 'Open',
    active: 'Active',
    needsVerification: 'Needs Verification',
    completed: 'Completed',
    statusLabels: {
      open: 'Open',
      claimed: 'Claimed',
      active: 'Active',
      in_progress: 'In progress',
      needs_verification: 'Needs verification',
      pending: 'Pending',
      planned: 'Planned',
      review: 'In review',
      blocked: 'Blocked',
      failed: 'Failed',
      done: 'Done',
      completed: 'Completed',
      cancelled: 'Cancelled',
      connected: 'Connected',
      ready: 'Ready',
      missing: 'Missing',
      error: 'Error',
      note: 'Note',
      request: 'Request',
      response: 'Response',
      handoff: 'Handoff'
    },
    priorityLabels: {
      low: 'Low',
      normal: 'Normal',
      high: 'High',
      urgent: 'Urgent'
    },
    claim: 'Claim',
    start: 'Start',
    block: 'Block',
    unblock: 'Unblock',
    complete: 'Complete',
    completeDirectly: 'Complete Directly',
    requestVerification: 'Request Verification',
    approveAndComplete: 'Approve & Complete',
    reportIssue: 'Report Issue',
    issueDescription: 'Issue Description',
    issueDescriptionPlaceholder: 'Describe what is incomplete or buggy...',
    reopenTask: 'Reopen task after reporting',
    reopen: 'Reopen',
    cancelledTerminal: 'This task is cancelled and remains terminal.',
    purge: 'Purge',
    purgeTask: 'Permanently delete task',
    purgeConfirm: 'Confirm deletion',
    purgeWarning: 'This action will permanently delete the task record and cannot be undone. Enter the task title to confirm:',
    purgeSuccess: 'Task purged successfully',
    purgeFailed: 'Purge failed',
    purgeOnlyCancelled: 'Only cancelled tasks can be purged',
    approve: 'Approve',
    reject: 'Reject',
    addNote: 'Add note',
    moreActions: 'More actions',
    notePlaceholder: 'Note or status reason',
    broadcastMessage: 'Send radio',
    sendRadioRequest: 'Send radio request',
    reply: 'Reply',
    replyTo: 'Reply to',
    thread: 'Thread',
    searchText: 'Search text',
    allSenders: 'All senders',
    allRecipients: 'All recipients',
    allTypes: 'All types',
    promoteToMemory: 'Promote to memory',
    triggerDispatch: 'Trigger dispatch',
    forceDispatch: 'Force run',
    limit: 'Limit',
    model: 'Model',
    modelPlaceholder: 'Optional, e.g. gpt-5.2',
    created: 'Created',
    assignee: 'Assignee',
    notes: 'Notes',
    review: 'Review',
    clear: 'Clear filters',
    cancel: 'Cancel',
    analyticsOverview: 'Analytics overview',
    tasksByStatus: 'Tasks by status',
    radioByType: 'Radio by type',
    relayByState: 'Relay by state',
    toolAutomation: 'Tool automation',
    missing: 'Missing',
    backupStorage: 'Backup storage',
    topProjects: 'Top projects',
    globalSearch: 'Global search',
    searchPlaceholder: 'Search memories, tasks, radio, or workflows',
    resultCount: 'Results',
    elapsed: 'Elapsed',
    range: 'Range',
    sort: 'Sort',
    relevance: 'Relevance',
    newest: 'Newest',
    oldest: 'Oldest',
    allRanges: 'All time',
    last24h: '24 hours',
    last7d: '7 days',
    last30d: '30 days',
    last90d: '90 days',
    facets: 'Facets',
    tags: 'Tags',
    results: 'Results',
    score: 'Score',
    backupSets: 'Backup sets',
    storageUsed: 'Storage used',
    retained: 'Retained',
    pruneCandidates: 'Prune candidates',
    createBackup: 'Create backup',
    backupReason: 'Backup reason',
    inspectBackup: 'Inspect files',
    previewRestore: 'Restore preview',
    backupFiles: 'Backup files',
    restoreSummary: 'Restore summary',
    backupPolicy: 'Backup policy',
    githubBackup: 'GitHub data backup',
    githubEnabled: 'Enable GitHub backup',
    githubRemote: 'Remote repository',
    githubRepoDir: 'Local repo directory',
    githubBranch: 'Branch',
    githubLastCommit: 'Last commit',
    githubLastError: 'Last error',
    githubPlaintext: 'Plaintext sensitive upload',
    githubSchedule: 'Schedule',
    githubNextRun: 'Next run',
    githubDryRun: 'Preview upload risk',
    githubLocalRun: 'Create local full backup',
    githubSave: 'Save GitHub config',
    githubAllowPlaintext: 'Allow plaintext sensitive upload',
    githubWarning: 'Backup uploads can include private user data. Verify the remote, access controls, retention policy, and recovery need before uploading.',
    githubWouldBlock: 'Plaintext upload would be blocked',
    githubNoRemote: 'Without a remote, only local backup is created',
    warnings: 'Warnings',
    files: 'Files',
    issues: 'Issues',
    upload: 'Upload',
    daily: 'Daily',
    weekly: 'Weekly',
    preSync: 'Pre-sync',
    changed: 'Changed',
    different: 'Different',
    missingCurrent: 'Missing current',
    unchanged: 'Unchanged',
    bytes: 'Bytes',
    path: 'Path',
    manual: 'Manual',
    workflowTotal: 'Total workflows',
    workflowActive: 'Active workflows',
    workflowReview: 'In review',
    workflowBlocked: 'Blocked workflows',
    createWorkflow: 'Create workflow',
    editWorkflow: 'Edit workflow',
    deleteWorkflow: 'Delete workflow',
    allStatuses: 'All statuses',
    planner: 'Planner',
    executor: 'Executor',
    reviewer: 'Reviewer',
    observer: 'Observer',
    workflowPlan: 'Plan',
    workflowAcceptance: 'Acceptance',
    workflowRisks: 'Risks',
    workflowLogs: 'Workflow logs',
    linkedItems: 'Linked items',
    startWorkflow: 'Start',
    markReview: 'Send to review',
    markDone: 'Mark done',
    workflowResult: 'Result',
    workflowNote: 'Note',
    workflowReviewEntry: 'Review note',
    workflowSignal: 'Send signal',
    viewExecutionGraph: 'View execution graph',
    signalTo: 'Send to',
    signalToPlaceholder: 'Recipient, e.g. reviewer or all',
    actionText: 'Text',
    actionTextPlaceholder: 'Enter text…',
    workflowTitleRequired: 'Workflow title is required',
    workflowTextRequired: 'Text is required',
    workflowSignalTargetRequired: 'Recipient is required',
    createdBy: 'Created by',
    noMatches: 'No matches',
    confirmDelete: 'Confirm delete',
    confirmDeleteWorkflow: 'This removes the workflow from the list. Confirm that only this workflow should be deleted.',
    refreshTools: 'Refresh tools',
    detectTools: 'Detect again',
    refreshCapabilities: 'Refresh capabilities',
    manageConfig: 'Manage config',
    installLocal: 'Write project',
    installGlobal: 'Write global',
    localTarget: 'Project target',
    globalTarget: 'Global target',
    rulePreview: 'Rule preview',
    previewUnavailable: 'No preview available',
    generatedAt: 'Generated at',
    successRate: 'Success rate',
    avgRuntime: 'Avg runtime',
    lastRun: 'Last run',
    activeDispatches: 'Active dispatches',
    totalRuns: 'Runs',
    runner: 'Runner',
    command: 'Command',
    healthReasons: 'Health reasons',
    declaredModels: 'Declared models',
    availableModels: 'Available models',
    strengths: 'Strengths',
    toolFilterAll: 'All tools',
    toolFilterReady: 'Ready',
    toolFilterConnected: 'Connected',
    toolFilterRunnable: 'Runnable',
    toolFilterMissing: 'Missing',
    toolFilterNeeds: 'Needs config',
    capabilitySummary: 'Capability summary',
    directCli: 'Direct CLI',
    sharedState: 'Shared state',
    autoDispatchLabel: 'Auto dispatch',
    snapshotLimit: 'Snapshot limit',
    coreLimit: 'Core limit',
    recentLimit: 'Recent limit',
    lockStaleMs: 'Lock timeout',
    languageSetting: 'Language',
    lightMode: 'Light',
    darkMode: 'Dark',
    saveSettings: 'Save settings',
    settingsSaved: 'Settings saved',
    actionSucceeded: 'Action completed',
    actionFailed: 'Action failed',
    pruneAfterSync: 'Prune after sync',
    repairSuggestions: 'Repair suggestions',
    healthScore: 'Health score',
    totalRecords: 'Total records',
    duplicateRecords: 'Duplicate records',
    corruptedRecords: 'Corrupted records',
    previewRepair: 'Preview repair',
    applyRepair: 'Apply repair',
    repairPlan: 'Repair plan',
    applied: 'Applied',
    dryRun: 'Dry run',
    confirmRepair: 'This operation changes local memory index data. Confirm that you reviewed the repair plan.',
    duplicateGroups: 'Duplicate groups',
    superseded: 'To supersede',
    settingsSyncSection: 'Sync and memory',
    settingsDashboardSection: 'Dashboard preferences',
    settingsBackupSection: 'Backup retention',
    memoryDir: 'Memory directory',
    shortcuts: 'Shortcuts',
    refreshSettings: 'Reload settings',
    invalidSettingsValue: 'Settings values must be positive integers',
    healthStatus: 'Health status',
    healthIssues: 'Health issues',
    duplicateRate: 'Duplicate rate',
    filesScanned: 'Files scanned',
    includesChecked: 'Includes checked',
    duplicateExamples: 'Duplicate examples',
    corruptedExamples: 'Corrupted examples',
    storageBreakdown: 'Storage breakdown',
    healthRawReport: 'Raw health report',
    noHealthIssues: 'No health issues',
    noHealthExamples: 'No examples',
    refreshHealth: 'Refresh health',
    repairLimit: 'Repair limit',
    totalActions: 'Total actions',
    ledgerRecordsUpdated: 'Updated records',
    corruptedRecovered: 'Recovered corrupted',
    corruptedArchived: 'Archived corrupted',
    repairPreviewEmpty: 'Preview repair first to generate a plan',
    confirmApply: 'Confirm apply',
    // Status badge variants (connection + message types)
    connected: 'Connected',
    ready: 'Ready',
    error: 'Error',
    note: 'Note',
    request: 'Request',
    response: 'Response',
    handoffBadge: 'Handoff',
    projectStatusLabels: {
      active: 'Active',
      paused: 'Paused',
      archived: 'Archived',
      hidden: 'Hidden'
    },
    allOption: 'All',
    // Memory panel + related entities
    memoryOverview: 'Memory overview',
    close: 'Close',
    relationContext: 'Related context',
    id: 'ID',
    time: 'Time',
    confirmedRelations: 'Confirmed relations',
    inferredContext: 'Inferred context',
    inferredNone: 'No inferred relations',
    noRelations: 'None',
    contentContext: 'Content context',
    loadingRelations: 'Loading relations…',
    // Lists / counts
    messageCount: 'messages',
    workflowCount: 'workflows',
    itemsSelected: 'selected',
    noMatchesProject: 'No matching projects',
    messagePlaceholder: 'Type a message…',
    titlePlaceholder: 'Enter workflow title',
    searchProjectPlaceholder: 'Search projects',
    // Tasks detail dialog
    executionInfo: 'Execution info',
    deliveryState: 'Delivery state',
    attempts: 'Attempts',
    progressLabel: 'Progress',
    reviewStatusLabel: 'Review status',
    recentIssue: 'Recent issue',
    activityLog: 'Activity log',
    taskLabel: 'Task',
    worktreeLabel: 'Worktree',
    // Projects edit dialog
    projectStatusLabel: 'Status',
    nameLabel: 'Name',
    displayNameLabel: 'Display name',
    typeLabel: 'Type',
    descriptionLabel: 'Description',
    aliasesLabel: 'Aliases (comma separated)',
    metadataLabel: 'Metadata (JSON)',
    resourcesLabel: 'Resources (JSON)',
    editProject: 'Edit project',
    saving: 'Saving…',
    invalidMetadataJson: 'Invalid metadata JSON',
    invalidResourcesJson: 'Invalid resources JSON',
    createdLabel: 'Created',
    updatedLabel: 'Updated',
    repo: 'Repo',
    feishu: 'Feishu',
    archive: 'Archive',
    // Agent execution panel
    agentExecutionCenter: 'Agent execution center',
    executionCockpit: 'EXECUTION COCKPIT',
    whatAgentsDoing: 'What agents are doing',
    sessionsLabel: 'sessions',
    needsAttention: 'Needs attention',
    reviewsLabel: 'reviews',
    markRead: 'mark read',
    noAgentSessions: 'No agent sessions yet. Waiting for dispatch or heartbeat.',
    unifiedTimeline: 'Unified timeline',
    noActivity: 'No activity yet.',
    worktreeReview: 'Worktree review',
    readyForReview: 'Ready for review',
    noWorktrees: 'No worktrees.',
    sessionStateLabels: {
      working: 'Working',
      idle: 'Idle',
      blocked: 'Blocked',
      waiting_review: 'Waiting review',
      done: 'Done',
      failed: 'Failed',
      stale: 'Stale'
    },
    // Credentials
    credentialId: 'Credential id',
    credentialSecret: 'Secret (hidden after save)',
    credentialEnv: 'Or environment variable',
    // Chat
    chat: {
      title: 'Chat',
      language: '中文',
      empty: 'No messages',
      placeholder: 'Type a message',
      send: 'Send',
      sending: 'Sending',
      to: 'To',
      project: 'Project',
      toolsUnavailable: 'No tools available',
      loadingTools: 'Loading available tools…'
    },
    skills: {
      title: 'Shared Skill Center',
      subtitle: 'Install once, reuse across projects and Agents.',
      syncTargets: 'Sync targets',
      refreshStatus: 'Refresh',
      syncToAgents: 'Sync to Agents',
      registrySkills: 'Registry Skills',
      enabledHere: 'Enabled here',
      discoveredLocally: 'Discovered locally',
      conflicts: 'Conflicts',
      targetVariants: 'Target variants',
      protectedCore: 'Protected core',
      canonicalRegistry: 'Canonical Skill Registry',
      searchPlaceholder: 'Search Skills',
      projectionNote: 'Agent directories are projections, not sources of truth',
      versions: 'versions',
      notSelected: 'not selected',
      updateAvailable: 'Update available',
      enabled: 'Enabled',
      disabled: 'Disabled',
      relations: 'Relations',
      enable: 'Enable',
      disable: 'Disable',
      emptyImported: 'No Skills imported yet. Import one from the local discovery list below.',
      localDiscovery: 'Local Skill Discovery',
      coreAdapterProtected: 'AMH core adapter; import disabled',
      targetVariantsNote: 'target-agent variants',
      contentConflict: 'content conflict; choose a version',
      duplicateMerged: 'identical sources merged',
      readyToImport: 'ready to import',
      sources: 'sources',
      viewRelations: 'View relations',
      protected: 'Protected',
      targetVariantBadge: 'Target variants',
      chooseVersion: 'Choose version',
      deduplicated: 'Deduplicated',
      importSelected: 'Import selected',
      importToAmh: 'Import to AMH',
      sharedCredentials: 'Shared Credentials',
      credentialNote: 'Configure credentials once; secret values are never returned to the page or Skill files.',
      noCredentials: 'No credentials configured'
    },
    extensions: {
      title: 'MCP Sync Center',
      subtitle: 'Manage MCP server configurations across Claude, Codex, Gemini, and OpenCode. Manage Skills on the Skills page.',
      refresh: 'Refresh',
      importAll: 'Import All',
      diff: 'Diff',
      registryMcp: 'Registry MCP',
      skillManagement: 'Skill management',
      openSkillsPage: 'Open Skills page',
      managed: 'Managed',
      syncedExtensions: 'Synced Extensions',
      conflicts: 'Conflicts',
      searchPlaceholder: 'Search extensions',
      all: 'All',
      applyElsePreview: 'Apply (else preview only)',
      applySync: 'Apply Sync',
      previewSync: 'Preview Sync',
      diffPreview: 'Diff Preview',
      toAdd: 'to add',
      current: 'current',
      currentBadge: 'CURRENT',
      add: 'ADD',
      conflict: 'CONFLICT',
      noDifferences: 'No differences',
      remove: 'Remove',
      removeFromList: 'Remove from synced list',
      removeQuestion: 'Remove?',
      confirmYes: 'Yes',
      confirmNo: 'No',
      unmanaged: 'Unmanaged',
      detected: 'Detected',
      notDetected: 'Not detected',
      mcp: 'MCP',
      skillKind: 'Skill',
      changes: 'changes',
      applied: 'Applied',
      previewOnly: 'Preview only',
      syncApplied: 'Sync applied',
      previewComplete: 'Preview complete, no files modified',
      emptySynced: 'No synced extensions yet. Import MCP here; manage Skills in the Skills page.'
    }
  }
}

export type DashboardCopy = typeof labels.zh

// Exported as Record<Language, DashboardCopy> so that indexing by language yields a
// single concrete type instead of a `zh | en` union, and so that any key added to one
// language but not the other is a compile error here rather than at every consumer.
export const dashboardLabels: Record<Language, DashboardCopy> = labels
